all: main.cpp MemoryStructure.cpp ScheduleProcessor.cpp FirstFit.cpp YourPolicy1.cpp YourPolicy2.cpp
	g++ --std=c++11 -m32 -g main.cpp MemoryStructure.cpp ScheduleProcessor.cpp FirstFit.cpp YourPolicy1.cpp YourPolicy2.cpp -o test
